# 1. Read the dataset

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import keras
from keras.models import Sequential
from keras.layers import Dense

In [3]:
dataset = pd.read_csv('bank.csv')

# 2. Drop the columns which are unique for all users like IDs

In [6]:
# Dropping columns like RowNumber, CustomerID, Surname since they do not matter in classification.
X = dataset.iloc[:,3:13].values # Credit Score through Estimated Salary
y = dataset.iloc[:, 13].values # Exited

# 3. Distinguish the feature and target set 

In [10]:
# Encoding categorical (string based) data. 
# Country: there are 3 options: France, Spain and Germany
# This will convert those strings into scalar values for analysis
label_X_country_encoder = LabelEncoder()
X[:,1] = label_X_country_encoder.fit_transform(X[:,1])

In [11]:
print(X[:8,1])

[0 2 0 0 2 2 0 1]


In [12]:
# Gender: there are 2 options: Male and Female
label_X_gender_encoder = LabelEncoder()
X[:,2] = label_X_gender_encoder.fit_transform(X[:,2])

In [13]:
# Converting the string features into their own dimensions.
countryhotencoder = OneHotEncoder(categorical_features = [1]) # 1 is the country column
X = countryhotencoder.fit_transform(X).toarray()

C:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [15]:
X = X[:,1:]

# 4.Divide the data set into Train and test sets

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

# 5. Normalize the train and test data

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

# 6. Initialize & build the model

In [23]:
classifier = Sequential()

## A hurestic tip is that the amount of nodes (dimensions) in your hidden layer should be the average of your input and output layers, which means that since we have 11 dimensions (representing Independent variables Note: Countries still compose only one dimension) and we are looking for a binary output, we calculate this to be  (11+1)÷2=6 .

In [24]:
classifier.add(Dense(activation = 'relu', input_dim = 11, units=6, kernel_initializer='uniform'))

Instructions for updating:
Colocations handled automatically by placer.


## Adding a second layer because we want to implement Deep Learning

## We will make our second hidden layer also have 6 nodes, just playing with the same arithmetic we used to determine the dimensions of the first hidden layer (average of your input and output layers)  (11+1)÷2=6 .

In [25]:
classifier.add(Dense(activation = 'relu', units=6, kernel_initializer='uniform')) 

## Output Layer

In [26]:
# We use the sigmoid because we want probability outcomes
classifier.add(Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform')) 

## Compiling the NN

In [27]:
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])


# 7. Print the Accuracy score and confusion matrix 

In [28]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 2s 312us/step - loss: 0.4988 - acc: 0.7955
Epoch 2/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.4306 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 223us/step - loss: 0.4252 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.4211 - acc: 0.8000
Epoch 5/100
8000/8000 [==============================] - 2s 204us/step - loss: 0.4177 - acc: 0.8220
Epoch 6/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.4158 - acc: 0.8261
Epoch 7/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4144 - acc: 0.8284
Epoch 8/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.4131 - acc: 0.8312
Epoch 9/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.4120 - acc: 0.8306
Epoch 10/100
8000/8000 [============================

8000/8000 [==============================] - 1s 138us/step - loss: 0.3947 - acc: 0.8339
Epoch 80/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.3952 - acc: 0.8357
Epoch 81/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3947 - acc: 0.8366
Epoch 82/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.3945 - acc: 0.8365
Epoch 83/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.3950 - acc: 0.8337
Epoch 84/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3947 - acc: 0.8372
Epoch 85/100
8000/8000 [==============================] - 1s 167us/step - loss: 0.3949 - acc: 0.8349
Epoch 86/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3946 - acc: 0.8346
Epoch 87/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3946 - acc: 0.8341
Epoch 88/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.3949 - acc: 0.8347
Epo

In [29]:
y_pred = classifier.predict(X_test)
print(y_pred)

[[0.18901563]
 [0.31477642]
 [0.17353457]
 ...
 [0.26141813]
 [0.08150676]
 [0.16828573]]


In [30]:
# To use the confusion Matrix, we need to convert the probabilities that a customer will leave the bank into the form true or false. So we will use the cutoff value 0.5 to indicate whether they are likely to exit or not.
y_pred = (y_pred > 0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1557   38]
 [ 277  128]]


In [32]:
print (((cm[0][0]+cm[1][1])*100)/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0]), '% of testing data was classified correctly')

84.25 % of testing data was classified correctly
